// src/openaiService.js
import constants from '@/settings/constant';
import axios from 'axios';

const GEMINI_API_KEY = constants.API_OPENAI; // Thay bằng key thật

export const gemini = axios.create({
  baseURL: 'https://generativelanguage.googleapis.com/v1beta/models',
  headers: {
    'Content-Type': 'application/json',
  },
  params: {
    key: GEMINI_API_KEY, // gán ở dạng query parameter
  },
});

const generatePrompt = (plainText: string, title: string): string => `
Please analyze the following news article carefully.

Take your time to process it thoroughly before responding.

Your task is to check two things:

1. How likely is this article generated by an AI? (based on writing style, coherence, repetitiveness, grammar, vocabulary, unnatural transitions, etc.)
2. How likely is this article copied from the internet, especially from news websites? (focus on long, exact matches or copied paragraphs — not just similar ideas or short phrases)

🧠 Important guidelines for determining if an article is AI-generated:
- Do NOT assume an article is AI just because it is short, simple, or lacks complexity.
- Consider it AI-generated only if multiple of the following signs appear:
  • The article has **unnatural flow or mechanical coherence**.
  • Sentences are **overly uniform in structure** or highly repetitive.
  • **Vocabulary is too clean, polished, and consistently advanced** — more so than what a human journalist would typically write without editing.
  • **Grammar is overly perfect** and lacks variation in sentence rhythm.
  • **Transitions are either missing or too formulaic**.
  • The content **lacks contextual nuance, emotion, or human insight** that would reflect a real writer's experience or perspective.

✅ Note: Many real news writers — especially beginners — may write in simple or factual ways. That does NOT mean their content is AI-generated.

🛑 Do not answer quickly. Think carefully and critically before producing your answer.

A copied article means it contains full sentences or paragraphs taken directly from existing sources online, especially from official or public news websites.

Return only the result in this JSON format, no explanations:

{
  "AI_generate": <percentage>,
  "copy_right": <percentage>
}

Here is the article to analyze:
Title: ${title}
"""
${plainText}
"""
`;

export const checkingNews = async (message: string, title: string) => {
  try {
    const response = await gemini.post('/gemini-2.0-flash:generateContent', {
      contents: [
        {
          parts: [
            {
              text: generatePrompt(message, title),
            },
          ],
        },
      ],
    });

    return response.data.candidates[0].content.parts[0].text;
  } catch (error) {
    console.error('Error checking news:', error);
  }
};
